name: Deploy xtools Web Demo

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Dependencies
        working-directory: ./example
        run: flutter pub get

      - name: Build Web App
        working-directory: ./example
        # The base-href must match your repository name exactly!
        run: flutter build web --base-href "/xtools/" --release

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./example/build/web